// <auto-generated />
using System;
using MercenaryGuild.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MercenaryGuild.Migrations
{
    [DbContext(typeof(GuildDbContext))]
    partial class GuildDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("MercenaryGuild.Models.Mercenary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mercenaries");
                });

            modelBuilder.Entity("MercenaryGuild.Models.Quest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTaken")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MercenaryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Reward")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MercenaryId");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("MercenaryGuild.Models.Quest", b =>
                {
                    b.HasOne("MercenaryGuild.Models.Mercenary", "Mercenary")
                        .WithMany("CompletedQuests")
                        .HasForeignKey("MercenaryId");

                    b.Navigation("Mercenary");
                });

            modelBuilder.Entity("MercenaryGuild.Models.Mercenary", b =>
                {
                    b.Navigation("CompletedQuests");
                });
#pragma warning restore 612, 618
        }
    }
}
